#!/bin/bash -e

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "${BRANCH}" = "develop" ]; then
    echo "you're on branch develop" 1>&2
fi
if [ "${BRANCH}" = "master" ]; then
    echo "you're on branch master" 1>&2
fi
if [ -z "${BRANCH}" -o "${BRANCH}" = "develop" -o "${BRANCH}" = "master" ]; then
    echo "please checkout the branch to merge to develop" 1>&2
    exit 1
fi

git submodule foreach "git commit -am '${*}'; git push"
git commit -am "${*}"; git push