#!/bin/bash -e

npm run build

aws ecr --profile scrypt get-login-password --region eu-central-2 \
| docker login --username AWS --password-stdin ${DOCKER_REPOSITORY}

DOCKER_TAG=develop npm run docker:build
DOCKER_TAG=develop npm run docker:push

scp ~/.docker/config.json operator.prod.scrypt.dev:.docker/
scp infrastructure/staging/{kong.yaml,docker-compose.yaml,.env} operator.prod.scrypt.dev:infrastructure/

ssh operator.prod.scrypt.dev 'cd infrastructure && docker-compose pull && docker-compose up --remove-orphans -d'
ssh operator.prod.scrypt.dev 'cd infrastructure && docker-compose logs -tf --tail 0'